restore version before changed to python 3
* workaround, which has to be reviewed
* remove error message

HexDump targets\rom\netXXL\secenc_rom.mem
scons: *** [targets\rom\netXXL\secenc_rom.mem] UnicodeEncodeError : 'ascii' codec can't encode character u'\ufffd' in position 4: ordinal not in range(128) Traceback (most recent call last):
scons: building terminated because of errors.
  File "C:\Users\Burkhard\.mbs\depack\org.scons\scons-local\scons-local-2.5.0_1\scons-local-2.5.0\SCons\Action.py", line 1054, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "C:\work\eclipse-2019-12\hboot_netxxl\mbs\site_scons\hexdump.py", line 53, in hexdump_action
    atSourceData.fromstring(strSourceData)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 4: ordinal not in range(128)